name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: claude-code-manager
            asset_name: claude-code-manager-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: claude-code-manager.exe
            asset_name: claude-code-manager-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: claude-code-manager
            asset_name: claude-code-manager-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: claude-code-manager
            asset_name: claude-code-manager-macos-aarch64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Prepare release assets
      run: |
        mkdir -p release-assets
        cp artifacts/claude-code-manager-linux-x86_64/claude-code-manager release-assets/claude-code-manager-linux-x86_64
        cp artifacts/claude-code-manager-macos-x86_64/claude-code-manager release-assets/claude-code-manager-macos-x86_64
        cp artifacts/claude-code-manager-macos-aarch64/claude-code-manager release-assets/claude-code-manager-macos-aarch64
        cp artifacts/claude-code-manager-windows-x86_64.exe/claude-code-manager.exe release-assets/claude-code-manager-windows-x86_64.exe
        chmod +x release-assets/claude-code-manager-*
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: release-assets/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}